### ISSUE TITLE
Instance Method Examples

### ISSUE THREAD

**Issue by bdenney** [learn-co-curriculum/python-p3-instance-methods#3] opened 2022-07-18 21:20 UTC
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195251?module_item_id=439027

### Concern

Module says that you must include “self” to indicate a method is an instance method and then the examples begin to (erroneously?) omit it

**Comment by jlboba** [comment] 2022-07-22 17:17
Closing as duplicate of #1 , has already been fixed. 

If I'm mistaken and this is a different error, please reopen and tag me!

**Closed as completed by jlboba** 2022-07-22 17:17 UTC
Labels: se curriculum, se python
